import {
  CHART3_ERROR,
  CHART3_FETCHING,
  CHART3_GET_SUCCRESS,
} from "../../constants";

const initialState = {
  results: {
    ชุมชนมณีแก้ว: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนดอนบน: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนบางแสนทาวเวอร์: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนตาลล้อม1: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนตาลล้อม2: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนบ้านเหมือง: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนพัฒนา2: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนดอนนารา: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนวัดกลางดอน: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนแสนสุข: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนมาบมะยม: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนท้ายตลาด: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนร่วมใจพัฒนา: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนบางแสนบน: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนหาดวอนนภา: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนบางเป้ง: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนหน้ามอ: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนโชคดี: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนสมใจนึก: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale:0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนหน้าเทศบาล: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนวัดแสนสุข: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนมุขแสนเจริญ1: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนมุขแสนเจริญ2: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนเขาสามมุข: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
    ชุมชนบ้านแหลมแท่น: {
      Elder: 0,
      ElderMale: 0,
      ElderFemale: 0,
      ElderSurvey: 0,
      ElderSurveyMale: 0,
      ElderSurveyFemale: 0,
      PerElderSurvey: 0,
    },
  },
  isFetching: null,
  isError: null,
};

export default (state = initialState, { type, payload }) => {
  switch (type) {
    case CHART3_GET_SUCCRESS:
      return { results: payload, isFetching: false, isError: false };
    case CHART3_FETCHING:
      return { ...state, isFetching: true, isError: false };
    case CHART3_ERROR:
      return { ...state, isFetching: false, isError: true };
    default:
      return state;
  }
};
