import {
  CHART8_ERROR,
  CHART8_FETCHING,
  CHART8_GET_SUCCRESS,
} from "../../constants";

const initialState = {
  results: {
    ชุมชนมณีแก้ว: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนดอนบน: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนบางแสนทาวเวอร์: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself:0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนตาลล้อม1: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนตาลล้อม2: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนบ้านเหมือง: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนพัฒนา2: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนดอนนารา: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนวัดกลางดอน: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนแสนสุข: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนมาบมะยม: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนท้ายตลาด: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนร่วมใจพัฒนา: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนบางแสนบน: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนหาดวอนนภา: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนบางเป้ง: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนหน้ามอ: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนโชคดี: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนสมใจนึก: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนหน้าเทศบาล: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนวัดแสนสุข: {
      Summary: 1,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 1,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนมุขแสนเจริญ1: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 1,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนมุขแสนเจริญ2: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนเขาสามมุข: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      },
      ชุมชนบ้านแหลมแท่น: {
      Summary: 0,
      Affiliation: 0,
      Yourself: 0,
      Gold: 0,
      Disabled: 0,
      Social: 0,
      Other: 0,
      PerAffiliation: 0,
      PerYourself: 0,
      PerGold: 0,
      PerDisabled: 0,
      PerSocial: 0,
      PerOther: 0
      }

  },
  isFetching: false,
  isError: false,
};

export default (state = initialState, { type, payload }) => {
  switch (type) {
    case CHART8_GET_SUCCRESS:
      return { results: payload, isFetching: false, isError: false };
    case CHART8_FETCHING:
      return { ...state, isFetching: true, isError: false };
    case CHART8_ERROR:
      return { ...state, isFetching: false, isError: true };
    default:
      return state;
  }
};
