import {
  CHART5_ERROR,
  CHART5_FETCHING,
  CHART5_GET_SUCCRESS,
} from "../../constants";

const initialState = {
  results: {
    ชุมชนมณีแก้ว: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนดอนบน: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนบางแสนทาวเวอร์: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนตาลล้อม1: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนตาลล้อม2: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนบ้านเหมือง: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนพัฒนา2: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนดอนนารา: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนวัดกลางดอน: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนแสนสุข: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนมาบมะยม: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนท้ายตลาด: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนร่วมใจพัฒนา: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนบางแสนบน: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนหาดวอนนภา: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนบางเป้ง: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนหน้ามอ: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนโชคดี: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนสมใจนึก: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนหน้าเทศบาล: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนวัดแสนสุข: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนมุขแสนเจริญ1: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนมุขแสนเจริญ2: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนเขาสามมุข: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
    ชุมชนบ้านแหลมแท่น: {
      Summary: 0,
      Alone: {
        Sum: 0,
        PerSum:0,
        AloneDay: 0,
        PerAloneDay: 0,
        AloneNight: 0,
        PerAloneNight: 0,
        AloneDayNight: 0,
        PerAloneDayNight: 0,
      },
      NotAlone: 0,
      PerNotAlone: 0,
    },
  },
  isFetching: false,
  isError: false,
};

export default (state = initialState, { type, payload }) => {
  switch (type) {
    case CHART5_GET_SUCCRESS:
      return { results: payload, isFetching: false, isError: false };
    case CHART5_FETCHING:
      return { ...state, isFetching: true, isError: false };
    case CHART5_ERROR:
      return { ...state, isFetching: false, isError: true };
    default:
      return state;
  }
};
